// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: user-account.proto

package user_account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录请求
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	VerifyCode    string                 `protobuf:"bytes,3,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_user_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

// 用户信息
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 登录响应
type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_user_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResp) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 注册请求
type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	VerifyCode    string                 `protobuf:"bytes,3,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_user_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

// 注册响应
type RegisterResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegisterStatus bool                   `protobuf:"varint,1,opt,name=registerStatus,proto3" json:"registerStatus,omitempty"`
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_user_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResp) GetRegisterStatus() bool {
	if x != nil {
		return x.RegisterStatus
	}
	return false
}

func (x *RegisterResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 用户详情（不含密码）
type UserDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender        int64                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Status        int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetail) Reset() {
	*x = UserDetail{}
	mi := &file_user_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetail) ProtoMessage() {}

func (x *UserDetail) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetail.ProtoReflect.Descriptor instead.
func (*UserDetail) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{5}
}

func (x *UserDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserDetail) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserDetail) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserDetail) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserDetail) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserDetail) GetGender() int64 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserDetail) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserDetail) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserDetail) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 获取用户详情请求
type GetUserDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailReq) Reset() {
	*x = GetUserDetailReq{}
	mi := &file_user_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailReq) ProtoMessage() {}

func (x *GetUserDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailReq.ProtoReflect.Descriptor instead.
func (*GetUserDetailReq) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserDetailReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 获取用户详情响应
type GetUserDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserDetail    *UserDetail            `protobuf:"bytes,1,opt,name=userDetail,proto3" json:"userDetail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDetailResp) Reset() {
	*x = GetUserDetailResp{}
	mi := &file_user_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDetailResp) ProtoMessage() {}

func (x *GetUserDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDetailResp.ProtoReflect.Descriptor instead.
func (*GetUserDetailResp) Descriptor() ([]byte, []int) {
	return file_user_account_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserDetailResp) GetUserDetail() *UserDetail {
	if x != nil {
		return x.UserDetail
	}
	return nil
}

var File_user_account_proto protoreflect.FileDescriptor

const file_user_account_proto_rawDesc = "" +
	"\n" +
	"\x12user-account.proto\x12\x04user\"\\\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1e\n" +
	"\n" +
	"verifyCode\x18\x03 \x01(\tR\n" +
	"verifyCode\"8\n" +
	"\bUserInfo\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"M\n" +
	"\tLoginResp\x12*\n" +
	"\buserInfo\x18\x01 \x01(\v2\x0e.user.UserInfoR\buserInfo\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"_\n" +
	"\vRegisterReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1e\n" +
	"\n" +
	"verifyCode\x18\x03 \x01(\tR\n" +
	"verifyCode\"H\n" +
	"\fRegisterResp\x12&\n" +
	"\x0eregisterStatus\x18\x01 \x01(\bR\x0eregisterStatus\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xf6\x01\n" +
	"\n" +
	"UserDetail\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x03R\x06gender\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\b \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\t \x01(\x03R\tupdatedAt\"*\n" +
	"\x10GetUserDetailReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"E\n" +
	"\x11GetUserDetailResp\x120\n" +
	"\n" +
	"userDetail\x18\x01 \x01(\v2\x10.user.UserDetailR\n" +
	"userDetail2\xb2\x01\n" +
	"\vUserAccount\x12+\n" +
	"\bLoginRpc\x12\x0e.user.LoginReq\x1a\x0f.user.LoginResp\x124\n" +
	"\vRegisterRpc\x12\x11.user.RegisterReq\x1a\x12.user.RegisterResp\x12@\n" +
	"\rGetUserDetail\x12\x16.user.GetUserDetailReq\x1a\x17.user.GetUserDetailRespB\x10Z\x0e./user_accountb\x06proto3"

var (
	file_user_account_proto_rawDescOnce sync.Once
	file_user_account_proto_rawDescData []byte
)

func file_user_account_proto_rawDescGZIP() []byte {
	file_user_account_proto_rawDescOnce.Do(func() {
		file_user_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_account_proto_rawDesc), len(file_user_account_proto_rawDesc)))
	})
	return file_user_account_proto_rawDescData
}

var file_user_account_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_account_proto_goTypes = []any{
	(*LoginReq)(nil),          // 0: user.LoginReq
	(*UserInfo)(nil),          // 1: user.UserInfo
	(*LoginResp)(nil),         // 2: user.LoginResp
	(*RegisterReq)(nil),       // 3: user.RegisterReq
	(*RegisterResp)(nil),      // 4: user.RegisterResp
	(*UserDetail)(nil),        // 5: user.UserDetail
	(*GetUserDetailReq)(nil),  // 6: user.GetUserDetailReq
	(*GetUserDetailResp)(nil), // 7: user.GetUserDetailResp
}
var file_user_account_proto_depIdxs = []int32{
	1, // 0: user.LoginResp.userInfo:type_name -> user.UserInfo
	5, // 1: user.GetUserDetailResp.userDetail:type_name -> user.UserDetail
	0, // 2: user.UserAccount.LoginRpc:input_type -> user.LoginReq
	3, // 3: user.UserAccount.RegisterRpc:input_type -> user.RegisterReq
	6, // 4: user.UserAccount.GetUserDetail:input_type -> user.GetUserDetailReq
	2, // 5: user.UserAccount.LoginRpc:output_type -> user.LoginResp
	4, // 6: user.UserAccount.RegisterRpc:output_type -> user.RegisterResp
	7, // 7: user.UserAccount.GetUserDetail:output_type -> user.GetUserDetailResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_account_proto_init() }
func file_user_account_proto_init() {
	if File_user_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_account_proto_rawDesc), len(file_user_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_account_proto_goTypes,
		DependencyIndexes: file_user_account_proto_depIdxs,
		MessageInfos:      file_user_account_proto_msgTypes,
	}.Build()
	File_user_account_proto = out.File
	file_user_account_proto_goTypes = nil
	file_user_account_proto_depIdxs = nil
}
