// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user-account.proto

package server

import (
	"context"

	"jieyuc.cn/jieyuc-aipm-agent/service/pb/user_account"
	"jieyuc.cn/jieyuc-aipm-agent/service/user-account/internal/logic"
	"jieyuc.cn/jieyuc-aipm-agent/service/user-account/internal/svc"
)

type UserAccountServer struct {
	svcCtx *svc.ServiceContext
	user_account.UnimplementedUserAccountServer
}

func NewUserAccountServer(svcCtx *svc.ServiceContext) *UserAccountServer {
	return &UserAccountServer{
		svcCtx: svcCtx,
	}
}

func (s *UserAccountServer) LoginRpc(ctx context.Context, in *user_account.LoginReq) (*user_account.LoginResp, error) {
	l := logic.NewLoginRpcLogic(ctx, s.svcCtx)
	return l.LoginRpc(in)
}

func (s *UserAccountServer) RegisterRpc(ctx context.Context, in *user_account.RegisterReq) (*user_account.RegisterResp, error) {
	l := logic.NewRegisterRpcLogic(ctx, s.svcCtx)
	return l.RegisterRpc(in)
}

func (s *UserAccountServer) GetUserDetail(ctx context.Context, in *user_account.GetUserDetailReq) (*user_account.GetUserDetailResp, error) {
	l := logic.NewGetUserDetailLogic(ctx, s.svcCtx)
	return l.GetUserDetail(in)
}
