// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package users

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	usersFieldNames          = builder.RawFieldNames(&Users{}, true)
	usersRows                = strings.Join(usersFieldNames, ",")
	usersRowsExpectAutoSet   = strings.Join(stringx.Remove(usersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	usersRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(usersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))

	cacheAipmUsersIdPrefix       = "cache:aipm:users:id:"
	cacheAipmUsersPhonePrefix    = "cache:aipm:users:phone:"
	cacheAipmUsersUserIdPrefix   = "cache:aipm:users:userId:"
	cacheAipmUsersUsernamePrefix = "cache:aipm:users:username:"
)

type (
	usersModel interface {
		Insert(ctx context.Context, data *Users) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Users, error)
		FindOneByPhone(ctx context.Context, phone string) (*Users, error)
		FindOneByUserId(ctx context.Context, userId string) (*Users, error)
		FindOneByUsername(ctx context.Context, username string) (*Users, error)
		Update(ctx context.Context, data *Users) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUsersModel struct {
		sqlc.CachedConn
		table string
	}

	Users struct {
		Id        int64        `db:"id"`         // 自增主键
		UserId    string       `db:"user_id"`    // 用户唯一ID
		Phone     string       `db:"phone"`      // 手机号码
		Username  string       `db:"username"`   // 用户名
		Password  string       `db:"password"`   // 加密后的密码
		Nickname  string       `db:"nickname"`   // 昵称
		Avatar    string       `db:"avatar"`     // 头像URL
		Gender    int64        `db:"gender"`     // 性别 0:未知 1:男 2:女
		Status    int64        `db:"status"`     // 状态 0:正常 1:禁用
		CreatedAt time.Time    `db:"created_at"` // 创建时间
		UpdatedAt time.Time    `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 删除时间 (用于软删除)
	}
)

func newUsersModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUsersModel {
	return &defaultUsersModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      `"aipm"."users"`,
	}
}

func (m *defaultUsersModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	aipmUsersIdKey := fmt.Sprintf("%s%v", cacheAipmUsersIdPrefix, id)
	aipmUsersPhoneKey := fmt.Sprintf("%s%v", cacheAipmUsersPhonePrefix, data.Phone)
	aipmUsersUserIdKey := fmt.Sprintf("%s%v", cacheAipmUsersUserIdPrefix, data.UserId)
	aipmUsersUsernameKey := fmt.Sprintf("%s%v", cacheAipmUsersUsernamePrefix, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aipmUsersIdKey, aipmUsersPhoneKey, aipmUsersUserIdKey, aipmUsersUsernameKey)
	return err
}

func (m *defaultUsersModel) FindOne(ctx context.Context, id int64) (*Users, error) {
	aipmUsersIdKey := fmt.Sprintf("%s%v", cacheAipmUsersIdPrefix, id)
	var resp Users
	err := m.QueryRowCtx(ctx, &resp, aipmUsersIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", usersRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByPhone(ctx context.Context, phone string) (*Users, error) {
	aipmUsersPhoneKey := fmt.Sprintf("%s%v", cacheAipmUsersPhonePrefix, phone)
	var resp Users
	err := m.QueryRowIndexCtx(ctx, &resp, aipmUsersPhoneKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where phone = $1 limit 1", usersRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, phone); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByUserId(ctx context.Context, userId string) (*Users, error) {
	aipmUsersUserIdKey := fmt.Sprintf("%s%v", cacheAipmUsersUserIdPrefix, userId)
	var resp Users
	err := m.QueryRowIndexCtx(ctx, &resp, aipmUsersUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where user_id = $1 limit 1", usersRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByUsername(ctx context.Context, username string) (*Users, error) {
	aipmUsersUsernameKey := fmt.Sprintf("%s%v", cacheAipmUsersUsernamePrefix, username)
	var resp Users
	err := m.QueryRowIndexCtx(ctx, &resp, aipmUsersUsernameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where username = $1 limit 1", usersRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, username); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) Insert(ctx context.Context, data *Users) (sql.Result, error) {
	aipmUsersIdKey := fmt.Sprintf("%s%v", cacheAipmUsersIdPrefix, data.Id)
	aipmUsersPhoneKey := fmt.Sprintf("%s%v", cacheAipmUsersPhonePrefix, data.Phone)
	aipmUsersUserIdKey := fmt.Sprintf("%s%v", cacheAipmUsersUserIdPrefix, data.UserId)
	aipmUsersUsernameKey := fmt.Sprintf("%s%v", cacheAipmUsersUsernamePrefix, data.Username)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, usersRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Phone, data.Username, data.Password, data.Nickname, data.Avatar, data.Gender, data.Status, data.DeletedAt)
	}, aipmUsersIdKey, aipmUsersPhoneKey, aipmUsersUserIdKey, aipmUsersUsernameKey)
	return ret, err
}

func (m *defaultUsersModel) Update(ctx context.Context, newData *Users) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	aipmUsersIdKey := fmt.Sprintf("%s%v", cacheAipmUsersIdPrefix, data.Id)
	aipmUsersPhoneKey := fmt.Sprintf("%s%v", cacheAipmUsersPhonePrefix, data.Phone)
	aipmUsersUserIdKey := fmt.Sprintf("%s%v", cacheAipmUsersUserIdPrefix, data.UserId)
	aipmUsersUsernameKey := fmt.Sprintf("%s%v", cacheAipmUsersUsernamePrefix, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, usersRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Id, newData.UserId, newData.Phone, newData.Username, newData.Password, newData.Nickname, newData.Avatar, newData.Gender, newData.Status, newData.DeletedAt)
	}, aipmUsersIdKey, aipmUsersPhoneKey, aipmUsersUserIdKey, aipmUsersUsernameKey)
	return err
}

func (m *defaultUsersModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAipmUsersIdPrefix, primary)
}

func (m *defaultUsersModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", usersRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUsersModel) tableName() string {
	return m.table
}
