// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetUserDetailResponse struct {
	UserDetail UserDetail `json:"userDetail"`
}

type LoginRequest struct {
	Phone      string `json:"phone"`
	Password   string `json:"password,optional"`
	VerifyCode string `json:"verifyCode,optional"`
}

type LoginResponse struct {
	UserInfo UserInfo `json:"userInfo"`
	Token    string   `json:"token"`
}

type RegisterRequest struct {
	Phone      string `json:"phone"`
	Password   string `json:"password"`
	VerifyCode string `json:"verifyCode"`
}

type RegisterResponse struct {
	RegisterStatus bool   `json:"registerStatus"`
	Msg            string `json:"msg"`
}

type UserDetail struct {
	UserId    string `json:"userId"`
	Phone     string `json:"phone"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Avatar    string `json:"avatar"`
	Gender    int64  `json:"gender"`
	Status    int64  `json:"status"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type UserInfo struct {
	Phone  string `json:"phone"`
	UserId string `json:"userId"`
}
