// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user-account.proto

package useraccount

import (
	"context"

	"jieyuc.cn/jieyuc-aipm-agent/service/pb/user_account"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserDetailReq  = user_account.GetUserDetailReq
	GetUserDetailResp = user_account.GetUserDetailResp
	LoginReq          = user_account.LoginReq
	LoginResp         = user_account.LoginResp
	RegisterReq       = user_account.RegisterReq
	RegisterResp      = user_account.RegisterResp
	UserDetail        = user_account.UserDetail
	UserInfo          = user_account.UserInfo

	UserAccount interface {
		LoginRpc(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		RegisterRpc(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
		GetUserDetail(ctx context.Context, in *GetUserDetailReq, opts ...grpc.CallOption) (*GetUserDetailResp, error)
	}

	defaultUserAccount struct {
		cli zrpc.Client
	}
)

func NewUserAccount(cli zrpc.Client) UserAccount {
	return &defaultUserAccount{
		cli: cli,
	}
}

func (m *defaultUserAccount) LoginRpc(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user_account.NewUserAccountClient(m.cli.Conn())
	return client.LoginRpc(ctx, in, opts...)
}

func (m *defaultUserAccount) RegisterRpc(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	client := user_account.NewUserAccountClient(m.cli.Conn())
	return client.RegisterRpc(ctx, in, opts...)
}

func (m *defaultUserAccount) GetUserDetail(ctx context.Context, in *GetUserDetailReq, opts ...grpc.CallOption) (*GetUserDetailResp, error) {
	client := user_account.NewUserAccountClient(m.cli.Conn())
	return client.GetUserDetail(ctx, in, opts...)
}
